language: java

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script:
  - ./gradlew test
  - if [ "$TRAVIS_JDK_VERSION" == "openjdk7" ]; then ./gradlew checkstyle; fi

after_success:
  - if [ "$TRAVIS_JDK_VERSION" == "openjdk7" ]; then ./gradlew coveralls; fi
